#!/bin/bash

# Fix App Icon - Replace Default React Native Icon with GROWSMART™ Icon
# This script updates the Android native resources to use the correct icon

echo "🔧 Fixing App Icon Configuration..."
echo ""

# Check if android folder exists
if [ ! -d "android" ]; then
    echo "⚠️  Android folder not found. Regenerating..."
    echo "📦 Running: npx expo prebuild --platform android"
    npx expo prebuild --platform android --no-install
    if [ ! -d "android" ]; then
        echo "❌ Failed to generate android folder. Please restore it from git or run:"
        echo "   git checkout android"
        echo "   Then run this script again."
        exit 1
    fi
fi

# Check if icon file exists
if [ ! -f "assets/images/growsmart-icon.png" ]; then
    echo "❌ Icon file not found: assets/images/growsmart-icon.png"
    exit 1
fi

echo "✅ Android folder found"
echo "✅ Icon file found: assets/images/growsmart-icon.png"
echo ""
echo "📝 Updating icon configuration..."
echo ""

# The icon should be automatically generated by Expo when building
# But we need to ensure app.json is correct (which it is)
echo "✅ app.json configuration is correct"
echo ""
echo "🔨 To apply the icon changes, run:"
echo "   cd android"
echo "   ./gradlew clean"
echo "   ./gradlew bundleRelease"
echo ""
echo "Or rebuild using Expo:"
echo "   npx expo run:android"
echo ""
echo "The icon will be automatically generated from:"
echo "  assets/images/growsmart-icon.png"
echo ""
